### ISSUE TITLE
Обращение к цвету.

### ISSUE THREAD

**Issue by c0rt** [optozorax/GraphWINApi#1]
Заменить `gwapi::grb(redValue, greenValue, blueValue)` на более удобное и логичное обращение к цвету.
Например: `RGB(redValue, greenValue, blueValue)` :)

**Comment by optozorax** [comment]
Это одно и то же, функция rgb находится в пространстве имен модуля для рисования. Большие буквы не используются потому, что в <windows.h> уже определено RGB. Тип цвета из windows.h и из этого модуля отличаются.
